USE master;

IF EXISTS (SELECT name
FROM sys.databases
WHERE name = 'QLBH')
BEGIN
    DROP DATABASE QLBH;
END

CREATE DATABASE QLBH;

USE QLBH;

IF EXISTS (SELECT TABLE_NAME
FROM QLBH.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'KHACH_HANG') 
BEGIN
    DROP TABLE KHACH_HANG
END
CREATE TABLE KHACH_HANG
(
    id INT IDENTITY(1,1),
    ten NVARCHAR(255) NOT NULL,
    email NVARCHAR(255) NOT NULL,
    sdt NVARCHAR(20) NOT NULL
)

IF EXISTS (SELECT TABLE_NAME
FROM QLBH.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'DON_HANG')
BEGIN
    DROP TABLE DON_HANG
END
CREATE TABLE DON_HANG
(
    id INT IDENTITY(1,1),
    khach_hang_id INT NOT NULL,
    ngay_dat DATE NOT NULL DEFAULT GETDATE(),
    tong_tien DECIMAL(18,2) NOT NULL CHECK (tong_tien >= 0)
)

IF EXISTS (SELECT TABLE_NAME
FROM QLBH.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'SAN_PHAM')
BEGIN
    DROP TABLE SAN_PHAM
END
CREATE TABLE SAN_PHAM
(
    id INT IDENTITY(1,1),
    ten NVARCHAR(255) NOT NULL,
    gia DECIMAL(18,2) NOT NULL CHECK (gia >= 0)
)

IF EXISTS (SELECT TABLE_NAME
FROM QLBH.INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'CHI_TIET_DON_HANG')
BEGIN
    DROP TABLE CHI_TIET_DON_HANG
END
CREATE TABLE CHI_TIET_DON_HANG
(
    don_hang_id INT NOT NULL,
    san_pham_id INT NOT NULL,
    so_luong INT NOT NULL CHECK (so_luong > 0)
)

IF EXISTS (SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE FROM QLBH.INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'KHACH_HANG' AND CONSTRAINT_NAME = 'PK_KHACH_HANG')
BEGIN
    ALTER TABLE KHACH_HANG DROP CONSTRAINT PK_KHACH_HANG;
END
ELSE
BEGIN
    ALTER TABLE KHACH_HANG ADD CONSTRAINT PK_KHACH_HANG PRIMARY KEY(id);
END
IF EXISTS (SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE FROM QLBH.INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'KHACH_HANG' AND CONSTRAINT_NAME = 'UNI_EMAIL')
BEGIN
    ALTER TABLE KHACH_HANG DROP CONSTRAINT UNI_EMAIL;
END
ELSE
BEGIN
    ALTER TABLE KHACH_HANG ADD CONSTRAINT UNI_EMAIL UNIQUE (email);
END
IF EXISTS (SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE FROM QLBH.INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'KHACH_HANG' AND CONSTRAINT_NAME = 'UNI_SDT')
BEGIN
    ALTER TABLE KHACH_HANG DROP CONSTRAINT UNI_SDT;
END
ELSE
BEGIN
    ALTER TABLE KHACH_HANG ADD CONSTRAINT UNI_SDT UNIQUE (sdt);
END

IF EXISTS (SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE FROM QLBH.INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'SAN_PHAM' AND CONSTRAINT_NAME = 'PK_SAN_PHAM')
BEGIN
    ALTER TABLE SAN_PHAM DROP CONSTRAINT PK_SAN_PHAM;
END
ELSE
BEGIN
    ALTER TABLE SAN_PHAM ADD CONSTRAINT PK_SAN_PHAM PRIMARY KEY(id);
END

IF EXISTS (SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE FROM QLBH.INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'DON_HANG' AND CONSTRAINT_NAME = 'PK_DON_HANG')
BEGIN
    ALTER TABLE DON_HANG DROP CONSTRAINT PK_DON_HANG;
END
ELSE
BEGIN
    ALTER TABLE DON_HANG ADD CONSTRAINT PK_DON_HANG PRIMARY KEY(id);
END
IF EXISTS (SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE FROM QLBH.INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'DON_HANG' AND CONSTRAINT_NAME = 'FK_DON_HANG_KHACH_HANG')
BEGIN
    ALTER TABLE DON_HANG DROP CONSTRAINT FK_DON_HANG_KHACH_HANG;
END
ELSE
BEGIN
    ALTER TABLE DON_HANG ADD CONSTRAINT FK_DON_HANG_KHACH_HANG FOREIGN KEY(khach_hang_id) REFERENCES KHACH_HANG(id);
END

IF EXISTS (SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE FROM QLBH.INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'CHI_TIET_DON_HANG' AND CONSTRAINT_NAME = 'PK_CHI_TIET_DON_HANG')
BEGIN
    ALTER TABLE CHI_TIET_DON_HANG DROP CONSTRAINT PK_CHI_TIET_DON_HANG;
END
ELSE
BEGIN
    ALTER TABLE CHI_TIET_DON_HANG ADD CONSTRAINT PK_CHI_TIET_DON_HANG PRIMARY KEY(don_hang_id, san_pham_id);
END
IF EXISTS (SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE FROM QLBH.INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'CHI_TIET_DON_HANG' AND CONSTRAINT_NAME = 'FK_CHI_TIET_DON_HANG_SAN_PHAM')
BEGIN
    ALTER TABLE CHI_TIET_DON_HANG DROP CONSTRAINT FK_CHI_TIET_DON_HANG_SAN_PHAM;
END
ELSE
BEGIN
    ALTER TABLE CHI_TIET_DON_HANG ADD CONSTRAINT FK_CHI_TIET_DON_HANG_SAN_PHAM FOREIGN KEY(san_pham_id) REFERENCES SAN_PHAM(id);
END
IF EXISTS (SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE FROM QLBH.INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'CHI_TIET_DON_HANG' AND CONSTRAINT_NAME = 'FK_CHI_TIET_DON_HANG_DON_HANG')
BEGIN
    ALTER TABLE CHI_TIET_DON_HANG DROP CONSTRAINT FK_CHI_TIET_DON_HANG_DON_HANG;
END
ELSE
BEGIN
    ALTER TABLE CHI_TIET_DON_HANG ADD CONSTRAINT FK_CHI_TIET_DON_HANG_DON_HANG FOREIGN KEY(don_hang_id) REFERENCES DON_HANG(id);
END