USE master;

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'UserApplicationDB')
BEGIN
    CREATE DATABASE UserApplicationDB; 
END

USE UserApplicationDB;

IF NOT EXISTS (SELECT TABLE_NAME FROM UserApplicationDB.INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'users')
BEGIN
    CREATE TABLE users(
        id INT,
        name NVARCHAR(50),
        age INT
    )
END

ALTER TABLE users ALTER COLUMN id INT NOT NULL;
ALTER TABLE users ALTER COLUMN name NVARCHAR(50) NOT NULL;

IF NOT EXISTS (SELECT 1 FROM UserApplicationDB.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'users' AND COLUMN_NAME = 'email')
BEGIN
    ALTER TABLE users ADD email NVARCHAR(50);
END
ELSE
BEGIN
    ALTER TABLE users ALTER COLUMN email NVARCHAR(50);
END

IF NOT EXISTS (SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE FROM UserApplicationDB.INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'users' 
AND CONSTRAINT_NAME = 'PK_users')
BEGIN
    ALTER TABLE users ADD CONSTRAINT PK_users PRIMARY KEY (id);
END
ELSE
BEGIN
    ALTER TABLE users DROP CONSTRAINT PK_users;
    ALTER TABLE users ADD CONSTRAINT PK_users PRIMARY KEY (id);
END

IF NOT EXISTS (SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE FROM UserApplicationDB.INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'users' 
AND CONSTRAINT_NAME = 'cs_email')
BEGIN
    ALTER TABLE users ADD CONSTRAINT cs_email UNIQUE (email);
END
ELSE
BEGIN
    ALTER TABLE users DROP CONSTRAINT cs_email;
    ALTER TABLE users ADD CONSTRAINT cs_email UNIQUE (email);
END

/*
    Viết script tạo table Roles (roleId, roleName, desc) lưu ý role Id là khoá chính, và role name không được trùng
*/

IF NOT EXISTS (SELECT TABLE_NAME FROM UserApplicationDB.INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Roles')
BEGIN
    CREATE TABLE Roles(
        roleId INT PRIMARY KEY,
        roleName NVARCHAR(50) UNIQUE,
        [desc] NVARCHAR(50)
    )
END
ELSE
BEGIN
    DROP TABLE Roles;
    CREATE TABLE Roles(
        roleId INT PRIMARY KEY,
        roleName NVARCHAR(50) UNIQUE,
        [desc] NVARCHAR(50)
    )
END
